apiVersion: k3d.io/v1alpha2
kind: Simple
name: k3d
servers: 1
agents: 1
image: rancher/k3s:v1.21.2-k3s1
options:
  k3d:
    wait: true
    timeout: "300s"
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
    disableHostIPInjection: false
  k3s:
    extraServerArgs:
      - --cluster-cidr=10.68.0.0/16
      - --service-cidr=10.98.0.0/16
      - --node-taint=node-role.kubernetes.io/master=true:NoSchedule
    extraAgentArgs: []
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true