apiVersion: v1
description: Use HostPath for persistent local storage with Kubernetes
name: local-path-provisioner
version: 0.0.20
appVersion: "v0.0.20"
keywords:
  - storage
  - hostpath
kubeVersion: ">=1.12.0-r0"
home: https://github.com/rancher/local-path-provisioner
sources:
  - https://github.com/rancher/local-path-provisioner.git
maintainers:
  - name: ebrianne
    email: eldwan35@gmail.com
    url: https://ebrianne.technolab.duckdns.org
